server:
  port: 8080

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/yktest
    username: root
    password: Ykkim123!
    hikari:
      max-lifetime: 30000
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
